name: Manual Triggered Job Example

permissions:
   contents: read

on:
  workflow_dispatch:
    inputs:
      files:
        required: false
        type: string
        default: |
          **.md **/**.md test/*.txt

jobs:
  test:
    name: Test changed-files
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      max-parallel: 7
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: true
          fetch-depth: 0

      - name: Run changed-files with defaults
        id: changed-files
        uses: ./

      - name: Show output
        run: |
          echo '${{ toJSON(steps.changed-files.outputs) }}'

      - name: Run changed-files with glob filtering
        id: changed-files-glob
        uses: ./
        with:
          files: ${{ inputs.files }}
          files_separator: " "  # Space delimited files (default is "\n")

      - name: Show output
        run: |
          echo '${{ toJSON(steps.changed-files-glob.outputs) }}'

      - name: Run changed-files with glob filtering and all_old_new_renamed_files
        id: changed-files-glob-all-old-new-renamed-files
        uses: ./
        with:
          include_all_old_new_renamed_files: true
          files: |
            test/*.txt

      - name: Show output
        run: |
          echo '${{ toJSON(steps.changed-files-glob-all-old-new-renamed-files.outputs) }}'
