name: Manual Test

on:
  workflow_dispatch:

jobs:
  test:
    name: Test changed-files
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        platform: [ubuntu-latest, ubuntu-22.04, windows-latest, macos-latest, macos-11, ubuntu-18.04, windows-2022]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Run changed-files with defaults
        id: changed-files
        uses: ./

      - name: Show output
        run: |
          echo '${{ toJSON(steps.changed-files.outputs) }}'

      - name: Run changed-files with glob filtering
        id: changed-files-glob
        uses: ./
        with:
          files: |
            test/*.txt

      - name: Show output
        run: |
          echo '${{ toJSON(steps.changed-files-glob.outputs) }}'
      
      - name: Run changed-files with glob filtering and all_old_new_renamed_files
        id: changed-files-glob-all-old-new-renamed-files
        uses: ./
        with:
          include_all_old_new_renamed_files: true
          files: |
            test/*.txt

      - name: Show output
        run: |
          echo '${{ toJSON(steps.changed-files-glob-all-old-new-renamed-files.outputs) }}'
