name: Format README.md

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  sync-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Run auto-doc
        uses: tj-actions/auto-doc@b10ceedffd794ec29a8fa8700529f40c1b64a951 # v3.6.0
        with:
          use_code_blocks: true
          use_major_version: true
          use_tag_commit_hash: true

      - name: Run remark
        uses: tj-actions/remark@10fc40701928cbafcc4a2d241679579d218144ff # v3

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@a1c6acee9df209257a246f2cc6ae8cb6581c1edf # v20.0.4
        id: verify_changed_files
        with:
          files: |
            README.md

      - name: README.md changed
        if: steps.verify_changed_files.outputs.files_changed == 'true'
        run: |
          echo "README.md has uncommitted changes"
          exit 1

      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          base: "main"
          labels: "merge when passing"
          title: "Updated README.md"
          branch: "chore/update-readme"
          commit-message: "Updated README.md"
          body: "Updated README.md"
          sign-commits: true
          token: ${{ secrets.GITHUB_TOKEN }}
