name: Workflow Run Example
on:
  workflow_run:
    workflows: [Matrix Example]
    types: [completed]

permissions:
  contents: read

jobs:
  on-success:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Get changed files
        id: changed-files
        uses: ./

      - name: Echo list of changed files on success
        run: |
          echo "Changed files on success:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"

  on-failure:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Get changed files
        id: changed-files
        uses: ./

      - name: Echo list of changed files on failure
        run: |
          echo "Changed files on failure:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"
